language: node_js
node_js:
  - "node"
install:
  - npm install
addons:
    chrome: beta
before_install:
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
